# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TinderClone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TinderClone
  pod 'Parse'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'SwiftyJSON'

end
